image: julia:1.13

pages:
  stage: deploy
  script:
    - julia --project=. -e 'using Pkg; Pkg.instantiate()'
    - julia --project=. test/runtests.jl
    - julia --project=. -e 'using Franklin; optimize(minify=false, prerender=false, clear=true, suppress_errors=false, fail_on_warning=true)'
    - mv __site public
  artifacts:
    paths:
      - public
  only:
    - main
